### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by daner5208** [FRNathan13/warface-emulator#1]
Help me pls ?
picture:
http://prntscr.com/g7ka8k

**Comment by daner5208** [comment]
@FRNathan13

**Comment by FRNathan13** [comment]
This is a common error, I am finishing mysql queries, this error is actually code xD. Mysql works normally however, the tables are missing, soon I'll make them available.

**Comment by FRNathan13** [comment]
Now support SQLITE3!
